"googleUserName": "notki.info@gmail.com"
"googleApplicationName": "GameStatistics"
"googleClientId": "481026810910-mqg4eehsnsd97igh8cjr4cle5amo2fv2.apps.googleusercontent.com"
"googleClientSecret": "hfcfgT6UcZNGAr-EEHKzDUev"
"repoRootPaths":
- "/Users/pawelfluder/Dropbox"
